### PR TITLE
fixed bar chart on negative values

### PR DESCRIPTION
**Pull request by vogievetsky**
- Added pre-calculation pattern to visualizations
- Fixed bar chart on negative values 

So the idea is that all vis now have a precalculate function where they could calculate some stuff once per data load instead on every render. This will be used for some heavy lifting later on.

### CODE REVIEW

**Comment by lorem--ipsum** [comment]
Out of curiosity, couldn't the `precalculate` function be inherited or accessed through composition, then overriden if needed ? It feels like there are redundant things across visualizations...

**Comment by vogievetsky** [comment]
It probably makes a lot of sense to make a visualization base class that all visualizations inherit, I was going to add some more logic to the bar chart `precalculate` and see where things fall. Also now with the `precalculate` logic extracted the data fetcher function could also be shared.

**Comment by lorem--ipsum** [comment]
Sweet, although I guess in order to keep PRs unit, we'll do that in another PR ?

**Comment by vogievetsky** [comment]
Yep another PR it will be.

**Comment by evasomething** [comment]
💧

**Pull request merged**
