### PR TITLE
Add "host" parameter to specify bind address

### PR DESCRIPTION
**Pull request by ei-grad**

### CODE REVIEW

**Comment by vogievetsky** [comment]
Hi, please change all names of `host` to `serverHost` and `HOST` to `SERVER_HOST`. Unfortunately `host` would be in conflict with something else that will be introduced shortly in https://github.com/implydata/pivot/tree/app-settings

**Comment by vogievetsky** [comment]
Also please add entry in `docs/configuration.md` below `port`

**Comment by vogievetsky** [comment]
This functionality is already addressed here: https://github.com/implydata/pivot/pull/219

**Comment by ei-grad** [comment]
Cool! Thanks.09.06.2016, 01:54, "Vadim Ogievetsky" <notifications@github.com>:This functionality is already addressed here: #219—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.￼

**Pull request closed without merging**
